### ISSUE TITLE
DFU does not work on a brand new board

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#1]
See https://rusefi.com/forum/viewtopic.php?p=39808#p39808 for a theory

**Comment by rusefillc** [comment]
@andreika-git is there a resistor we can remove from hellen72b to try the fix? would it be a useful test?

**Comment by andreika-git** [comment]
The only fix for Hellen72b I can think of is to carefully cut a trace between A22 and PB2 here:
![image](https://user-images.githubusercontent.com/15104768/108115898-77fd4800-70a3-11eb-8931-bf693ab8cb1d.png)

**Comment by andreika-git** [comment]
The solution for the next module rev: add a track jumper to the MCU module near the R128 to connect A22 and PB2 only for H7 configs. (AUX3 (A22) input cannot have a pull-up because it causes a conflict with BOOT1 on PB2 (COMP1_INP on H7))

Also, for the next Hellen72 revision we can optimize the input connections even further:
IN_CLUTCH -> RES3 (free EXTI5 and use EXTI8)
IN_EGR -> AUX3 (move from ADC3 to ADC12)
IN_NEUTRAL -> SENS3 (use EXTI5)
IN_FUEL_LEVEL -> AUX2 (move from ADC3 to ADC12)

**Comment by andreika-git** [comment]
Added a tiny jumper resistor to the MCU module (not populated by default):
![image](https://user-images.githubusercontent.com/15104768/108810021-d437fe80-75b2-11eb-9bf7-f1d835eddc5a.png)
