### ISSUE TITLE
do we survive 5va output power to GND?

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#119]
See https://github.com/rusefi/rusefi/issues/3559

**Comment by rusefillc** [comment]
First order of business is to document current state on MCU module wiki page?

**Comment by rusefillc** [comment]
I have about 400 of TLS115D0EJXUMA1

let's please move to TLS115D0EJXUMA1 those are cheap and very resilient

**Comment by rusefillc** [comment]
Documented on https://github.com/andreika-git/hellen-one/wiki/module-mcu#supply-output

**Comment by rusefillc** [comment]
at this point we do NOT have a unified hellen solution - we simply slap TLS115 on all boards individually. maybe that should be revisited but that's the way it is right now

@beermoneymotorsports FYI

**Comment by rusefillc** [comment]
reopening:

@andreika-git what do you think about adding TLS115 on the back of MCU module to make a uniform fix for more of hellen boards?

**Comment by andreika-git** [comment]
> reopening:
> 
> @andreika-git what do you think about adding TLS115 on the back of MCU module to make a uniform fix for more of hellen boards?

Adding TLS115 on the back is hard on its own, but also it requires some additional conditions:
![image](https://user-images.githubusercontent.com/15104768/148602304-758dc7cc-99cf-471b-842f-b9539de48713.png)
Two more capacitors - hand soldering on the back side?
And +12V source which is unobtainable inside the mcu module.

Maybe we can just try replacing the L101 inductor with a resettable PTC 0805 fuse. For example, SMD0805-050_C66452, which has 0.5A hold current rating and low enough resistance - 0.15 Ohms (but only 6V rated, which is fine for normal operation as +5V power line, but maybe not good enough for "shorting to +12V" protection). Maybe I could even try to fit a larger 1206 footprint instead of 0805 (which gives us even better PTC fuses), but I'm not sure.
